### PR TITLE
fix: borderRadius calculation

### PR DESCRIPTION
**Pull request by mrousavy**

### CODE REVIEW

**Comment by andreialecu** [comment]
From what I can see by this change, it removes support for border radius on the native component itself, correct?

I have already worked around it in the app I'm working on by applying the border radius on the parent element, and using overflow hidden.

**Comment by mrousavy** [comment]
Exactly

**Comment by andreialecu** [comment]
I see. Well, that would definitely fix it :)

A possible suggestion on how to handle this for both Android and iOS and not require the end-user to add a wrapper could be to change this:

https://github.com/mrousavy/react-native-blurhash/blob/5ada6064a8978fde46f511182e28949c016d1a59/src/index.tsx#L129-L140

To add the wrapper itself, and extract the borderRadius from the parent style.

Something like:
```ts
	render() {
		const { style, rest } = this.props;
		return (
            <View style={[style, { overflow: "hidden" }]}>
				  <NativeBlurhashView
					  {...this.props}
					  onLoadStart={this._onLoadStart}
					  onLoadEnd={this._onLoadEnd}
					  // @ts-expect-error
					  onLoadError={this._onLoadError}
				  />
			</View>
		);
	}
```

(untested)

**Comment by mrousavy** [comment]
Right, that's a good point. I'll try that, thanks!

**Comment by andreialecu** [comment]
(btw, offtopic but I noticed there's both a `yarn.lock` and `package-lock.json` in the repo, perhaps one should be git ignored)

**Pull request merged**
