### PR TITLE
Windows Fixes

### PR DESCRIPTION
**Pull request by jonthysell**
This PR contains various fixes for the Windows C++/WinRT implementation, separated into different commits.

Some are straight up fixes, others just recommendations.

### CODE REVIEW

**Comment by jonthysell** [comment]
@mrousavy The example app will build and launch, but I still haven't' successfully loaded the JS from metro. I can push another commit when I can get that working to unblock you.

One other thing - you're deving against RNW 0.62 but your peer requirement is for >= 0.60. As it stands, I don't believe your current code will work on RNW 0.60 or 0.61. There were a lot of tooling changes over the 0.60-0.62 timeframe that stabilized in 0.62.

With some additional work you could make 0.61 work following a pattern I've used for react-native-camera and react-native-video. RNW 0.60 would be a stretch however.

Since what you currently have is only going to build against RNW 0.62 anyway, if you're comfortable with explicitly bumping the min requirement for RNW to 0.62, I have some more suggested changes that will help future-proof you for RNW 0.63 and autolinking.

**Comment by mrousavy** [comment]
Awesome, thanks so much for your help. I don't mind using 0.62 for my min version 👍

**Comment by jonthysell** [comment]
Fixed the example app / metro issues. Sometimes metro doesn't respond right away and I have to hit reload in the app to get the bundle to actually load, but I'm guessing getting this far unblocks you:

image

Note, when I hit the button the app crashes, but I leave getting the module to do what you want in your hands.

I'll have one more commit with the min 0.62 and future-proofing stuff I mentioned before.

**Comment by jonthysell** [comment]
Ok, hopefully this unblocks you.

**Comment by mrousavy** [comment]
Yes, it will! Thank you for your contribution 🎉 ❤️

**Pull request merged**
